INSERT INTO aitunes.product (product_id, title, release_date, price, label_id, genre_id, format_id, in_stock) VALUES (1, 'The Sin and the Sentence', '2017-10-20', 20, 3, 1, 1, true);
INSERT INTO aitunes.product (product_id, title, release_date, price, label_id, genre_id, format_id, in_stock) VALUES (2, 'The Sin and the Sentence', '2017-10-20', 40, 3, 1, 2, true);
INSERT INTO aitunes.product (product_id, title, release_date, price, label_id, genre_id, format_id, in_stock) VALUES (3, 'The Sin and the Sentence', '2017-10-20', 15, 3, 1, 4, true);
INSERT INTO aitunes.product (product_id, title, release_date, price, label_id, genre_id, format_id, in_stock) VALUES (4, 'Random Acces Memories', '2013-05-13', 25, 2, 3, 1, true);
INSERT INTO aitunes.product (product_id, title, release_date, price, label_id, genre_id, format_id, in_stock) VALUES (5, 'Random Acces Memories', '2013-05-13', 40, 2, 3, 2, true);
INSERT INTO aitunes.product (product_id, title, release_date, price, label_id, genre_id, format_id, in_stock) VALUES (6, 'Random Acces Memories', '2013-05-13', 15, 2, 3, 4, true);
INSERT INTO aitunes.product (product_id, title, release_date, price, label_id, genre_id, format_id, in_stock) VALUES (7, 'Kill ''Em All', '1983-07-25', 10, 6, 4, 1, true);
INSERT INTO aitunes.product (product_id, title, release_date, price, label_id, genre_id, format_id, in_stock) VALUES (8, 'Kill ''Em All', '1983-07-25', 25, 6, 4, 2, true);
INSERT INTO aitunes.product (product_id, title, release_date, price, label_id, genre_id, format_id, in_stock) VALUES (9, 'Kill ''Em All', '1983-07-25', 10, 6, 4, 3, true);
INSERT INTO aitunes.product (product_id, title, release_date, price, label_id, genre_id, format_id, in_stock) VALUES (10, 'Kill ''Em All', '1983-07-25', 10, 6, 4, 4, false);
INSERT INTO aitunes.product (product_id, title, release_date, price, label_id, genre_id, format_id, in_stock) VALUES (11, 'Master of Puppets', '1986-03-03', 15, 5, 4, 1, true);
INSERT INTO aitunes.product (product_id, title, release_date, price, label_id, genre_id, format_id, in_stock) VALUES (12, 'Master of Puppets', '1986-03-03', 25, 5, 4, 2, false);
INSERT INTO aitunes.product (product_id, title, release_date, price, label_id, genre_id, format_id, in_stock) VALUES (13, 'Master of Puppets', '1986-03-03', 10, 5, 4, 3, false);
INSERT INTO aitunes.product (product_id, title, release_date, price, label_id, genre_id, format_id, in_stock) VALUES (14, 'Master of Puppets', '1986-03-03', 10, 5, 4, 4, true);
INSERT INTO aitunes.product (product_id, title, release_date, price, label_id, genre_id, format_id, in_stock) VALUES (15, 'Master of the Rings', '1994-07-08', 12, 7, 5, 1, true);
INSERT INTO aitunes.product (product_id, title, release_date, price, label_id, genre_id, format_id, in_stock) VALUES (16, 'Master of the Rings', '1994-07-08', 25, 7, 5, 2, true);
INSERT INTO aitunes.product (product_id, title, release_date, price, label_id, genre_id, format_id, in_stock) VALUES (17, 'Master of the Rings', '1994-07-08', 8, 7, 5, 3, true);
INSERT INTO aitunes.product (product_id, title, release_date, price, label_id, genre_id, format_id, in_stock) VALUES (18, 'Master of the Rings', '1994-07-08', 10, 7, 5, 4, true);
INSERT INTO aitunes.product (product_id, title, release_date, price, label_id, genre_id, format_id, in_stock) VALUES (19, '¿Dónde Jugarán Los Niños?', '1992-10-27', 10, 4, 6, 1, true);
INSERT INTO aitunes.product (product_id, title, release_date, price, label_id, genre_id, format_id, in_stock) VALUES (20, '¿Dónde Jugarán Los Niños?', '1992-10-27', 8, 4, 6, 3, true);